baseURL = "https://elaine-chenma.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-resume"


[params]
    firstName = "Chen (Elaine)"
    lastName = "MA"
    address = "San Francisco, CA"
    phone = "415(216)-6507"
    contactNote = "Data Analyst"
    profileImage = "img/personal_pic.png"
    email = "elainemazju@gmail.com"
    description = "Data enthusiast with cross-functional working experience and acumen product sense"
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    #showOpenSource = true
    #showPublications = true
    showExperience = true
    showEducation = true

    #showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/chen-ma/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/elaine-chenma"

# [[params.handles]]
#     name = "Bitbucket"
#     link = "https://bitbucket.org/eddiewebb/"
#
# [[params.handles]]
#     name = "Stack Overflow"
#     link = "https://stackoverflow.com/users/story/82880"
#     icon = "stack-overflow"
#
# [[params.handles]]
#     name = "Keybase"
#     link = "https://keybase.io/edwardawebb"
#     icon = "keybase"

[params.google.analytics]
    trackerID = "XX-123446-01"
